import type { BackupPayload,AppTicket,AppTechnician,RouteStartPoint } from "../data/AppDataContext";
import type { Filial } from "../data/filiais";
import { requireSupabaseBrowserClient } from "../lib/supabase/client";
import { saveByNaturalKey } from "./database";

type CategoryResult={created:number;updated:number;ignored:number;errors:string[]};
export type MigrationReport={analysts:CategoryResult;technicians:CategoryResult;branches:CategoryResult;tickets:CategoryResult;routes:CategoryResult;stops:CategoryResult;startedAt:string;finishedAt:string};
const category=():CategoryResult=>({created:0,updated:0,ignored:0,errors:[]});
const text=(value:unknown)=>String(value??"").trim();
const dateTime=(value?:string)=>value?(/^\d{4}-\d{2}-\d{2}$/.test(value)?`${value}T12:00:00.000Z`:value):null;
const numericId=(uuid:string)=>{let hash=0;for(let index=0;index<uuid.length;index++)hash=(hash*31+uuid.charCodeAt(index))|0;return Math.abs(hash)||1};

export function summarizeBackup(payload:BackupPayload){return{tickets:payload.tickets.length,analysts:payload.analysts.length,technicians:payload.technicians.length,branches:payload.branches.length,routes:new Set(payload.tickets.filter(item=>item.tech&&item.date&&item.planningStatus!=="nao_planejado").map(item=>`${item.tech}-${item.date}`)).size}}

export async function migrateBackupToCloud(payload:BackupPayload,onProgress?:(message:string)=>void):Promise<MigrationReport>{
  const client=requireSupabaseBrowserClient();
  const report:MigrationReport={analysts:category(),technicians:category(),branches:category(),tickets:category(),routes:category(),stops:category(),startedAt:new Date().toISOString(),finishedAt:""};
  const analystIds=new Map<string,string>(),technicianIds=new Map<string,string>(),branchIds=new Map<string,string>(),routeIds=new Map<string,string>(),ticketIds=new Map<string,string>();
  const run=async(name:keyof Omit<MigrationReport,"startedAt"|"finishedAt">,label:string,task:()=>Promise<{row:Record<string,any>;created:boolean}>)=>{try{const result=await task();report[name][result.created?"created":"updated"]++;return result.row}catch(reason){report[name].errors.push(`${label}: ${reason instanceof Error?reason.message:String(reason)}`);return null}};

  onProgress?.("Migrando analistas…");
  for(const item of payload.analysts){if(!text(item.name)){report.analysts.ignored++;continue}const row=await run("analysts",item.name,()=>saveByNaturalKey("analysts","name",item.name,{name:item.name,email:item.email||null,phone:item.phone||null,department:item.sector||null,initials:item.initials||null,color:item.color||null,notes:item.notes||null,active:item.active!==false}));if(row)analystIds.set(item.name.toLowerCase(),row.id)}

  onProgress?.("Migrando técnicos…");
  for(const item of payload.technicians){if(!text(item.name)){report.technicians.ignored++;continue}const parts=item.city.split(",");const row=await run("technicians",item.name,()=>saveByNaturalKey("technicians","name",item.name,{name:item.name,color:item.color||null,active:item.active!==false,start_latitude:item.latitude??null,start_longitude:item.longitude??null,start_address:item.address||null,start_city:parts[0]?.trim()||null,start_uf:parts[1]?.trim()||null,start_time:item.startTime||null,end_time:item.endTime||null,initials:item.initials||null,notes:item.notes||null}));if(row)technicianIds.set(item.name.toLowerCase(),row.id)}

  onProgress?.("Migrando filiais…");
  for(const item of payload.branches){if(!text(item.nome)){report.branches.ignored++;continue}const keyColumn=item.cnpj?"cnpj":"branch_number",keyValue=item.cnpj||item.numeroFilial;const row=await run("branches",item.numeroFilial||item.nome,()=>saveByNaturalKey("branches",keyColumn,keyValue,{branch_number:item.numeroFilial||null,name:item.nome,cnpj:item.cnpj||null,address:item.endereco||null,neighborhood:item.bairro||null,city:item.cidade||null,uf:item.uf||null,cep:item.cep||null,phone:item.telefone||null,state_registration:item.inscricaoEstadual||null,latitude:item.latitude,longitude:item.longitude,active:item.status==="ativo",geocode_status:item.geocodeStatus,data_status:item.statusDados,source:item.fonteCoordenada||null,map_link:item.linkMapa||null,notes:item.observacoes||null}));if(row){branchIds.set(String(item.id),row.id);branchIds.set(`number:${item.numeroFilial}`,row.id);if(item.cnpj)branchIds.set(`cnpj:${item.cnpj}`,row.id)}}

  const planned=payload.tickets.filter(item=>item.tech&&item.date&&item.planningStatus!=="nao_planejado");
  const routeGroups=new Map<string,AppTicket[]>();planned.forEach(ticket=>{const key=`${ticket.tech}-${ticket.date}`;routeGroups.set(key,[...(routeGroups.get(key)||[]),ticket])});
  onProgress?.("Migrando rotas…");
  for(const [key,items] of Array.from(routeGroups.entries())){const first=items[0],technicianId=technicianIds.get(first.tech!.toLowerCase());if(!technicianId){report.routes.ignored++;report.routes.errors.push(`${key}: técnico não localizado no banco.`);continue}const savedStart=payload.routeStartPoints[key];try{const existing=await client.from("routes").select("*").eq("technician_id",technicianId).eq("route_date",first.date!).maybeSingle();if(existing.error)throw existing.error;const input={technician_id:technicianId,route_date:first.date!,status:items.some(item=>item.planningStatus==="rota_confirmada")?"confirmada":"rascunho",start_type:savedStart?.type||null,start_description:savedStart?.description||null,start_address:savedStart?.address||null,start_city:savedStart?.city||null,start_uf:savedStart?.uf||null,start_latitude:savedStart?.latitude??null,start_longitude:savedStart?.longitude??null,estimated_minutes:items.reduce((sum,item)=>sum+(item.duration||0),0)};const query=existing.data?client.from("routes").update(input).eq("id",existing.data.id):client.from("routes").insert(input);const result=await query.select().single();if(result.error)throw result.error;report.routes[existing.data?"updated":"created"]++;routeIds.set(key,result.data.id)}catch(reason){report.routes.errors.push(`${key}: ${reason instanceof Error?reason.message:String(reason)}`)}}

  onProgress?.("Migrando chamados…");
  for(const item of payload.tickets){if(!text(item.number)||!text(item.desc)){report.tickets.ignored++;continue}const routeKey=item.tech&&item.date?`${item.tech}-${item.date}`:"";const row=await run("tickets",item.number,()=>saveByNaturalKey("tickets","ticket_number",item.number,{ticket_number:item.number,branch_id:branchIds.get(String(item.branchId))||branchIds.get(`cnpj:${item.branchCnpj}`)||branchIds.get(`number:${item.branchNumber}`)||null,analyst_id:analystIds.get(text(item.analistaResponsavel||item.analyst||"Não definido").toLowerCase())||null,technician_id:item.tech?technicianIds.get(item.tech.toLowerCase())||null:null,branch_name:item.branch||null,city:item.city||null,uf:item.uf||null,address:item.address||null,latitude:item.latitude??null,longitude:item.longitude??null,description:item.desc,status:item.status,urgency:item.urgency,planned_date:item.date||null,estimated_minutes:item.duration||60,opened_at:dateTime(item.openedAt),deadline_at:dateTime(item.dueAt),notes:item.notes||null,planning_status:item.planningStatus||"nao_planejado",route_id:routeIds.get(routeKey)||null,route_order:item.routeOrder||null}));if(row)ticketIds.set(item.number,row.id)}

  onProgress?.("Migrando paradas das rotas…");
  for(const [key,items] of Array.from(routeGroups.entries())){const routeId=routeIds.get(key);if(!routeId)continue;for(const item of items){const ticketId=ticketIds.get(item.number);if(!ticketId){report.stops.ignored++;continue}try{const existing=await client.from("route_stops").select("id").eq("route_id",routeId).eq("ticket_id",ticketId).maybeSingle();if(existing.error)throw existing.error;const input={route_id:routeId,ticket_id:ticketId,stop_order:item.routeOrder||1,latitude:item.latitude??null,longitude:item.longitude??null};const query=existing.data?client.from("route_stops").update(input).eq("id",existing.data.id):client.from("route_stops").insert(input);const result=await query;if(result.error)throw result.error;report.stops[existing.data?"updated":"created"]++}catch(reason){report.stops.errors.push(`${item.number}: ${reason instanceof Error?reason.message:String(reason)}`)}}}
  report.finishedAt=new Date().toISOString();
  return report;
}

export async function loadCloudBackup():Promise<BackupPayload|null>{
  const client=requireSupabaseBrowserClient();
  const [analystsResult,techniciansResult,branchesResult,ticketsResult,routesResult]=await Promise.all([client.from("analysts").select("*"),client.from("technicians").select("*"),client.from("branches").select("*"),client.from("tickets").select("*"),client.from("routes").select("*")]);
  const error=analystsResult.error||techniciansResult.error||branchesResult.error||ticketsResult.error||routesResult.error;if(error)throw error;
  const analystRows=analystsResult.data||[],technicianRows=techniciansResult.data||[],branchRows=branchesResult.data||[],ticketRows=ticketsResult.data||[],routeRows=routesResult.data||[];
  if(!analystRows.length&&!technicianRows.length&&!branchRows.length&&!ticketRows.length)return null;
  const technicians:AppTechnician[]=technicianRows.map(row=>({id:numericId(row.id),cloudId:row.id,name:row.name,initials:row.initials||row.name.slice(0,2).toUpperCase(),color:row.color||"#2563eb",city:[row.start_city,row.start_uf].filter(Boolean).join(", "),address:row.start_address||"",startTime:row.start_time?.slice(0,5)||"08:00",endTime:row.end_time?.slice(0,5)||"17:00",active:row.active!==false,notes:row.notes||"",latitude:row.start_latitude,longitude:row.start_longitude}));
  const branches:Filial[]=branchRows.map(row=>({id:numericId(row.id),cloudId:row.id,numeroFilial:row.branch_number||"",nome:row.name,cidade:row.city||"",uf:row.uf||"",endereco:row.address||"",bairro:row.neighborhood||"",cep:row.cep||"",cnpj:row.cnpj||"",inscricaoEstadual:row.state_registration||"",telefone:row.phone||"",status:row.active===false?"desativado":"ativo",latitude:row.latitude===null?null:Number(row.latitude),longitude:row.longitude===null?null:Number(row.longitude),geocodeStatus:row.geocode_status==="preenchida"?"preenchida":"pendente",statusDados:["ok","incompleto","sem_coordenadas"].includes(row.data_status)?row.data_status:"ok",fonteCoordenada:row.source||"Supabase",linkMapa:row.map_link||"",observacoes:row.notes||""} as Filial));
  const branchMap=new Map(branchRows.map((row,index)=>[row.id,branches[index]])),techMap=new Map(technicianRows.map(row=>[row.id,row.name])),analystMap=new Map(analystRows.map(row=>[row.id,row.name]));
  const tickets:AppTicket[]=ticketRows.map(row=>{const branch=branchMap.get(row.branch_id);return{id:numericId(row.id),cloudId:row.id,number:row.ticket_number,branch:row.branch_name||branch?.nome||"Filial não definida",branchId:branch?.id,branchNumber:branch?.numeroFilial,branchCnpj:branch?.cnpj,city:row.city||branch?.cidade||"",uf:row.uf||branch?.uf,address:row.address||branch?.endereco||"",latitude:row.latitude===null?null:Number(row.latitude),longitude:row.longitude===null?null:Number(row.longitude),desc:row.description,status:row.status,urgency:row.urgency,tech:techMap.get(row.technician_id),date:row.planned_date||undefined,duration:row.estimated_minutes||60,analistaResponsavel:analystMap.get(row.analyst_id)||"Não definido",analyst:analystMap.get(row.analyst_id)||"Não definido",openedAt:row.opened_at?.slice(0,10),dueAt:row.deadline_at?.slice(0,10),notes:row.notes||undefined,routeOrder:row.route_order||undefined,routeId:row.route_id||undefined,planningStatus:row.planning_status} as AppTicket});
  const routeStartPoints:Record<string,RouteStartPoint>={};routeRows.forEach(row=>{const tech=techMap.get(row.technician_id);if(!tech)return;routeStartPoints[`${tech}-${row.route_date}`]={type:row.start_type||"tecnico",description:row.start_description||`Ponto padrão de ${tech}`,address:row.start_address||"",city:row.start_city||"",uf:row.start_uf||"",latitude:row.start_latitude===null?null:Number(row.start_latitude),longitude:row.start_longitude===null?null:Number(row.start_longitude),notes:row.notes||""} as RouteStartPoint});
  return{schema:"rotasmart-backup",version:2,exportedAt:new Date().toISOString(),tickets,technicians,branches,routeStartPoints,analysts:analystRows.map(row=>({id:row.id,name:row.name,email:row.email||"",phone:row.phone||undefined,sector:row.department||undefined,active:row.active!==false,color:row.color||"#2563eb",initials:row.initials||row.name.slice(0,2).toUpperCase(),notes:row.notes||"",createdAt:row.created_at,updatedAt:row.updated_at}))};
}
