import {calculateRouteDistance,isValidCoordinate,type CoordinatePoint} from "../utils/distance";

export type RouteGeometryPoint=[number,number];
export type RoadRoutingProvider="tomtom"|"openrouteservice"|"graphhopper"|"osrm"|"google";
export type RouteSource=RoadRoutingProvider|"haversine";
export type RouteCalculation={source:RouteSource;distanceKm:number|null;durationMinutes:number|null;geometry:RouteGeometryPoint[];fallback:boolean;calculatedAt:string;warning?:string};

const validGeometry=(value:unknown):value is RouteGeometryPoint[]=>Array.isArray(value)&&value.length>=2&&value.every(point=>Array.isArray(point)&&point.length===2&&isValidCoordinate(point[0],point[1]));
export function calculateFallbackRoute(points:CoordinatePoint[],warning?:string):RouteCalculation{const valid=Array.isArray(points)?points.filter(point=>isValidCoordinate(point.latitude,point.longitude)):[];const distanceKm=valid.length>=2?calculateRouteDistance(valid):null;return{source:"haversine",distanceKm,durationMinutes:distanceKm===null?null:Math.ceil(distanceKm),geometry:valid.map(point=>[point.latitude!,point.longitude!]),fallback:true,calculatedAt:new Date().toISOString(),warning}}
export function normalizeRouteResponse(value:unknown):RouteCalculation|null{const data=value&&typeof value==="object"?value as Record<string,unknown>:null;if(!data||!(["tomtom","openrouteservice","graphhopper","osrm","google"] as unknown[]).includes(data.source)||!Number.isFinite(data.distanceKm)||!Number.isFinite(data.durationMinutes)||!validGeometry(data.geometry))return null;return{source:data.source as RoadRoutingProvider,distanceKm:Number(data.distanceKm),durationMinutes:Number(data.durationMinutes),geometry:data.geometry as RouteGeometryPoint[],fallback:false,calculatedAt:new Date().toISOString(),warning:typeof data.warning==="string"?data.warning:undefined}}
export async function calculateRoadRoute(points:CoordinatePoint[],provider:RoadRoutingProvider="tomtom"):Promise<RouteCalculation>{const valid=Array.isArray(points)?points.filter(point=>isValidCoordinate(point.latitude,point.longitude)):[];const fallback=calculateFallbackRoute(valid);if(valid.length<2)return{...fallback,warning:"Não há coordenadas suficientes para calcular a rota por ruas."};try{const response=await fetch("/api/routing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({coordinates:valid.map(point=>[point.longitude,point.latitude]),provider})});const payload=await response.json().catch(()=>null) as any;const normalized=normalizeRouteResponse(payload);if(response.ok&&normalized)return normalized;if(response.ok&&payload?.source==="haversine")return{...fallback,warning:typeof payload.warning==="string"?payload.warning:"TomTom indisponível. Usando estimativa em linha reta."};const message=payload&&typeof payload==="object"&&"error" in payload?String(payload.error):"Não foi possível calcular a rota por ruas.";return{...fallback,warning:message}}catch{return{...fallback,warning:"Não foi possível calcular a rota por ruas. Usando estimativa em linha reta."}}}
