import type { RouteRow,RouteStopRow } from "../types/database";
import { requireSupabaseBrowserClient } from "../lib/supabase/client";
export type RouteInput=Partial<Omit<RouteRow,"id"|"created_at"|"updated_at">>&{technician_id:string;route_date:string;status:string};
export async function listRoutes(dateFrom?:string,dateTo?:string){let query=requireSupabaseBrowserClient().from("routes").select("*").order("route_date");if(dateFrom)query=query.gte("route_date",dateFrom);if(dateTo)query=query.lte("route_date",dateTo);const {data,error}=await query;if(error)throw error;return data as RouteRow[]}
export async function getRouteById(id:string){const {data,error}=await requireSupabaseBrowserClient().from("routes").select("*").eq("id",id).single();if(error)throw error;return data as RouteRow}
export async function createRoute(input:RouteInput){const {data,error}=await requireSupabaseBrowserClient().from("routes").insert(input).select().single();if(error)throw error;return data as RouteRow}
export async function updateRouteRecord(id:string,input:Partial<RouteInput>){const {data,error}=await requireSupabaseBrowserClient().from("routes").update(input).eq("id",id).select().single();if(error)throw error;return data as RouteRow}
export async function removeRoute(id:string){const {error}=await requireSupabaseBrowserClient().from("routes").delete().eq("id",id);if(error)throw error}
export async function listRouteStops(routeId:string){const {data,error}=await requireSupabaseBrowserClient().from("route_stops").select("*").eq("route_id",routeId).order("stop_order");if(error)throw error;return data as RouteStopRow[]}
export async function replaceRouteStops(routeId:string,stops:Array<Pick<RouteStopRow,"ticket_id"|"stop_order"|"latitude"|"longitude">>){const client=requireSupabaseBrowserClient();const removed=await client.from("route_stops").delete().eq("route_id",routeId);if(removed.error)throw removed.error;if(!stops.length)return[];const {data,error}=await client.from("route_stops").insert(stops.map(stop=>({...stop,route_id:routeId}))).select();if(error)throw error;return data as RouteStopRow[]}

export type CloudRoutePlanTicket={id:string;order:number;latitude?:number|null;longitude?:number|null};
export async function reconcileRoutePlan(input:{technicianId:string;date:string;planningStatus:"nao_planejado"|"em_rota_rascunho"|"rota_confirmada";tickets:CloudRoutePlanTicket[]}){
 const client=requireSupabaseBrowserClient();const {data:{user}}=await client.auth.getUser();const actor=user?.id||null;const existing=await client.from("routes").select("*").eq("technician_id",input.technicianId).eq("route_date",input.date).maybeSingle();if(existing.error)throw existing.error;
 const routeStatus=input.planningStatus==="rota_confirmada"?"confirmada":"rascunho";const routeQuery=existing.data?client.from("routes").update({status:routeStatus,updated_by:actor}).eq("id",existing.data.id):client.from("routes").insert({technician_id:input.technicianId,route_date:input.date,status:routeStatus,created_by:actor,updated_by:actor});const routeResult=await routeQuery.select().single();if(routeResult.error)throw routeResult.error;const routeId=routeResult.data.id as string;
 const oldStops=await client.from("route_stops").select("ticket_id").eq("route_id",routeId);if(oldStops.error)throw oldStops.error;const desiredIds=new Set(input.tickets.map(ticket=>ticket.id));const removedIds=(oldStops.data||[]).map(stop=>stop.ticket_id as string).filter(id=>!desiredIds.has(id));
 const clearStops=await client.from("route_stops").delete().eq("route_id",routeId);if(clearStops.error)throw clearStops.error;if(removedIds.length){const cleared=await client.from("tickets").update({technician_id:null,planned_date:null,route_id:null,route_order:null,planning_status:"nao_planejado",updated_by:actor}).in("id",removedIds);if(cleared.error)throw cleared.error}
 for(const ticket of input.tickets){const payload:Record<string,unknown>={technician_id:input.technicianId,planned_date:input.date,route_id:routeId,route_order:ticket.order,planning_status:input.planningStatus,updated_by:actor};if(input.planningStatus==="rota_confirmada")payload.status="Programado";const updated=await client.from("tickets").update(payload).eq("id",ticket.id);if(updated.error)throw updated.error}
 if(input.tickets.length){const stops=await client.from("route_stops").insert(input.tickets.map(ticket=>({route_id:routeId,ticket_id:ticket.id,stop_order:ticket.order,latitude:ticket.latitude??null,longitude:ticket.longitude??null})));if(stops.error)throw stops.error}
 return routeResult.data as RouteRow;
}
