import type { TicketRow } from "../types/database";
import { requireSupabaseBrowserClient } from "../lib/supabase/client";

export type TicketFilters={status?:string;analystId?:string;technicianId?:string;plannedDate?:string};
export type TicketInput=Partial<Omit<TicketRow,"id"|"created_at"|"updated_at">>&{ticket_number:string;description:string;status:string;urgency:string};
function databaseError(action:string,error:unknown){if(error instanceof Error)return error;const value=error&&typeof error==="object"?error as Record<string,unknown>:{};const details=[value.message,value.details,value.hint,value.code].filter(Boolean).map(String);return new Error(`${action}: ${details.join(" — ")||String(error)}`)}
export async function listTickets(filters:TicketFilters={}){let query=requireSupabaseBrowserClient().from("tickets").select("*").eq("active",true).is("deleted_at",null).order("created_at",{ascending:false});if(filters.status)query=query.eq("status",filters.status);if(filters.analystId)query=query.eq("analyst_id",filters.analystId);if(filters.technicianId)query=query.eq("technician_id",filters.technicianId);if(filters.plannedDate)query=query.eq("planned_date",filters.plannedDate);const {data,error}=await query;if(error)throw error;return data as TicketRow[]}
export async function getTicketById(id:string){const {data,error}=await requireSupabaseBrowserClient().from("tickets").select("*").eq("id",id).single();if(error)throw error;return data as TicketRow}
export async function createTicketRecord(input:TicketInput){const {data,error}=await requireSupabaseBrowserClient().from("tickets").insert(input).select().single();if(error)throw error;return data as TicketRow}
export async function updateTicketRecord(id:string,input:Partial<TicketInput>){const {data,error}=await requireSupabaseBrowserClient().from("tickets").update(input).eq("id",id).select().single();if(error)throw error;return data as TicketRow}
export async function updateTicketAdministrativeStatus(id:string,status:string){const client=requireSupabaseBrowserClient();const {data:{user}}=await client.auth.getUser();const {data,error}=await client.from("tickets").update({status,updated_by:user?.id||null}).eq("id",id).select("id,status,updated_at").single();if(error)throw error;return data}
export async function cancelTicketRecord(id:string){const client=requireSupabaseBrowserClient();const stops=await client.from("route_stops").delete().eq("ticket_id",id);if(stops.error)throw stops.error;const {data,error}=await client.from("tickets").update({status:"Cancelado",technician_id:null,planned_date:null,planning_status:"nao_planejado",route_id:null,route_order:null}).eq("id",id).select().single();if(error)throw error;return data as TicketRow}
export async function deleteTicketRecord(id:string){const {error}=await requireSupabaseBrowserClient().from("tickets").delete().eq("id",id);if(error)throw error}
export async function deleteTicketAndStops(id:string){const client=requireSupabaseBrowserClient();const {data,error}=await client.rpc("soft_delete_ticket",{p_ticket_id:id});if(error){if(error.code==="PGRST202"||String(error.message||"").includes("soft_delete_ticket"))throw new Error("A função de exclusão ainda não existe no banco. Execute novamente a migration_v2_2_sync_delete_fix.sql no Supabase.");throw databaseError("O Supabase recusou a exclusão",error)}if(!data)throw new Error("O Supabase não confirmou a exclusão do chamado.");return data}
export async function unplanTicketRecord(id:string){const client=requireSupabaseBrowserClient();const stops=await client.from("route_stops").delete().eq("ticket_id",id);if(stops.error)throw stops.error;const {data,error}=await client.from("tickets").update({technician_id:null,planned_date:null,route_id:null,route_order:null,planning_status:"nao_planejado"}).eq("id",id).select().single();if(error)throw error;return data as TicketRow}
export async function assignTicketToRoute(ticketId:string,routeId:string,order:number){return updateTicketRecord(ticketId,{route_id:routeId,route_order:order,planning_status:"rota_confirmada",status:"Programado"})}
export async function removeTicketFromRoute(ticketId:string){return updateTicketRecord(ticketId,{route_id:null,route_order:null,planning_status:"nao_planejado"})}
