"use client";
import {useRef,useState} from "react";
import {AlertTriangle,Check,Download,FileSpreadsheet,Sparkles,UploadCloud} from "lucide-react";
import {useAppData,type AppTicket} from "../data/AppDataContext";

const statuses:AppTicket["status"][]=["Novo","Programado","Aguardando compra","Aguardando entrega","Em atendimento","Concluído","Fechado"];
const urgencies:AppTicket["urgency"][]=["Alta","Média","Baixa"];
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
const aliases:Record<string,string>={chamado:"number",nchamado:"number",numero:"number",numerochamado:"number",filial:"branch",numerofilial:"branchNumber",nfilial:"branchNumber",cidade:"city",descricao:"desc",status:"status",urgencia:"urgency",tecnico:"tech",tecnicoplanejado:"tech",dataplanejada:"date",tempoestimado:"duration",dataabertura:"openedAt",datalimite:"dueAt",analista:"analyst",observacoes:"notes"};

function parseCsv(text:string){
 const delimiter=(text.split(/\r?\n/,1)[0].match(/;/g)||[]).length>(text.split(/\r?\n/,1)[0].match(/,/g)||[]).length?";":",";const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;
 for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(char===delimiter&&!quoted){row.push(cell.trim());cell=""}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=""}else cell+=char}row.push(cell.trim());if(row.some(Boolean))rows.push(row);if(rows.length<2)return [];
 const headers=rows[0].map(header=>aliases[normalize(header)]||normalize(header));return rows.slice(1).map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]||""])));
}

export default function ImportTickets({flash}:{flash:(message:string)=>void}){
 const {tickets,setTickets,branches}=useAppData();const input=useRef<HTMLInputElement>(null);const [fileName,setFileName]=useState("");const [preview,setPreview]=useState<AppTicket[]>([]);const [errors,setErrors]=useState<string[]>([]);
 const readFile=async(file?:File)=>{if(!file)return;if(!file.name.toLowerCase().endsWith(".csv")){setErrors(["Nesta versão, selecione um arquivo CSV."]);setPreview([]);return}const rows=parseCsv(await file.text());const issues:string[]=[];const parsed=rows.map((raw,index)=>{const number=String(raw.number||"").trim();if(!number)issues.push(`Linha ${index+2}: número do chamado ausente.`);const branchNumber=String(raw.branchNumber||raw.branch||"").trim();const branch=branches.find(item=>item.numeroFilial===branchNumber)||branches.find(item=>normalize(item.nome)===normalize(String(raw.branch||"")));const status=statuses.includes(raw.status as AppTicket["status"])?raw.status as AppTicket["status"]:"Novo";const urgency=urgencies.includes(raw.urgency as AppTicket["urgency"])?raw.urgency as AppTicket["urgency"]:"Baixa";return {id:Date.now()+index,number:number||`#REVISAR-${index+1}`,branch:branch?.nome||String(raw.branch||"Filial não localizada"),branchNumber:branch?.numeroFilial||branchNumber||undefined,city:branch?`${branch.cidade}, ${branch.uf}`:String(raw.city||"Cidade não informada"),address:branch?.endereco||"Endereço não informado",desc:String(raw.desc||"Sem descrição"),status,urgency,tech:String(raw.tech||"")||undefined,date:String(raw.date||"")||undefined,duration:Number(raw.duration)||60,openedAt:String(raw.openedAt||"")||undefined,dueAt:String(raw.dueAt||"")||undefined,analyst:String(raw.analyst||"")||undefined,notes:String(raw.notes||"")||undefined,planningStatus:"nao_planejado",reviewBranch:!branch} satisfies AppTicket});setFileName(file.name);setPreview(parsed);setErrors(issues)};
 const existing=preview.filter(item=>tickets.some(ticket=>ticket.number===item.number)).length;const fresh=preview.length-existing;
 const importNow=()=>{setTickets(current=>{let next=[...current];preview.forEach(incoming=>{const index=next.findIndex(ticket=>ticket.number===incoming.number);if(index<0)next.push(incoming);else{const old=next[index];next[index]={...old,...incoming,id:old.id,tech:old.tech,date:old.date,routeOrder:old.routeOrder,routeId:old.routeId,planningStatus:old.planningStatus,duration:old.duration,notes:old.notes}}});return next});flash(`${preview.length} chamados importados com sucesso`);setPreview([]);setFileName("")};
 const downloadModel=()=>{const content="numeroChamado;filial;cidade;descricao;status;urgencia;tecnicoPlanejado;dataPlanejada;tempoEstimado;dataAbertura;dataLimite;analista;observacoes\n#5001;1;Jaraguá do Sul;Descrição do chamado;Novo;Alta;;;60;;;;";const url=URL.createObjectURL(new Blob(["\uFEFF"+content],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="modelo-importacao-rotasmart.csv";link.click();URL.revokeObjectURL(url)};
 return <><div className="pagehead"><div><h1>Importar chamados</h1><p>Selecione um CSV real para atualizar a operação.</p></div><div className="page-actions"><button className="btn secondary" onClick={downloadModel}><Download size={17}/>Baixar modelo CSV</button></div></div><div className="import-grid"><div className="panel import-main"><div className="step"><span>1</span><div><h3>Envie seu arquivo</h3><p>Formato aceito nesta versão: CSV com até 10 MB.</p></div></div><input ref={input} hidden type="file" accept=".csv,text/csv" onChange={event=>readFile(event.target.files?.[0])}/><div className={`dropzone ${fileName?"has-file":""}`} onClick={()=>input.current?.click()}>{fileName?<><div className="file-icon"><FileSpreadsheet/></div><div><b>{fileName}</b><span>{preview.length} registros encontrados</span></div><Check className="file-check"/></>:<><div className="upload-icon"><UploadCloud/></div><b>Clique para selecionar um CSV</b><span>Nenhum arquivo de teste é carregado automaticamente.</span></>}</div>{errors.map(error=><p className="warning-text" key={error}><AlertTriangle size={15}/>{error}</p>)}{fileName&&<><div className="step second"><span>2</span><div><h3>Prévia da importação</h3><p>Confira o que será criado e atualizado.</p></div></div><div className="import-summary"><div><Sparkles/><b>{fresh}</b><span>Novos chamados</span></div><div><Download/><b>{existing}</b><span>Serão atualizados</span></div><div><AlertTriangle/><b>{errors.length+preview.filter(item=>item.reviewBranch).length}</b><span>Para revisar</span></div></div><button className="btn primary import-button" disabled={!preview.length} onClick={importNow}><UploadCloud size={17}/>Importar {preview.length} chamados</button></>}</div><div className="panel rules"><h3>Como funciona</h3><div className="rule"><span>1</span><div><b>Identificamos repetidos</b><p>O número do chamado é o identificador único.</p></div></div><div className="rule"><span>2</span><div><b>Atualizamos dados do arquivo</b><p>Status, descrição, urgência e dados de origem são atualizados.</p></div></div><div className="rule"><span>3</span><div><b>Preservamos o planejamento</b><p>Técnico, data, rota, ordem, tempo estimado e notas internas são preservados.</p></div></div></div></div></>;
}
