"use client";
import {useRef,useState} from "react";
import {AlertTriangle,Check,Download,FileSpreadsheet,Sparkles,UploadCloud} from "lucide-react";
import {useAppData,type AppTicket} from "../data/AppDataContext";
import {isValidCoordinate} from "../utils/distance";

const MAX_FILE_SIZE=10*1024*1024;
const statuses:AppTicket["status"][]=["Novo","Programado","Aguardando compra","Aguardando entrega","Em atendimento","Concluído","Fechado","Cancelado"];
const urgencies:AppTicket["urgency"][]=["Alta","Média","Baixa"];
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
const aliases:Record<string,string>={chamado:"number",nchamado:"number",numero:"number",numerochamado:"number",filial:"branch",numerofilial:"branchNumber",nfilial:"branchNumber",cnpj:"branchCnpj",cidade:"city",descricao:"desc",status:"status",urgencia:"urgency",tecnico:"tech",tecnicoplanejado:"tech",dataplanejada:"date",tempoestimado:"duration",dataabertura:"openedAt",datalimite:"dueAt",analista:"analistaResponsavel",analistaresponsavel:"analistaResponsavel",responsavel:"analistaResponsavel",observacoes:"notes"};

function parseCsv(text:string){const first=text.split(/\r?\n/,1)[0];const delimiter=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?";":",";const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(char===delimiter&&!quoted){row.push(cell.trim());cell=""}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=""}else cell+=char}row.push(cell.trim());if(row.some(Boolean))rows.push(row);if(rows.length<2)return[];const headers=rows[0].map(header=>aliases[normalize(header)]||normalize(header));return rows.slice(1).map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]||""])))}

export default function ImportTickets({flash}:{flash:(message:string)=>void}){
 const {tickets,setTickets,branches}=useAppData();const input=useRef<HTMLInputElement>(null);const [fileName,setFileName]=useState("");const [preview,setPreview]=useState<AppTicket[]>([]);const [errors,setErrors]=useState<string[]>([]);
 const readFile=async(file?:File)=>{if(!file)return;setFileName(file.name);setPreview([]);if(!file.name.toLowerCase().endsWith(".csv")){setErrors(["Selecione um arquivo CSV. XLSX ainda não é aceito nesta versão."]);return}if(file.size>MAX_FILE_SIZE){setErrors(["O arquivo excede o limite de 10 MB."]);return}const rows=parseCsv(await file.text());if(!rows.length){setErrors(["O CSV está vazio ou não possui cabeçalho e registros."]);return}const issues:string[]=[];const seen=new Set<string>();const parsed=rows.map((raw,index)=>{const line=index+2;const number=String(raw.number||"").trim();const normalizedNumber=normalize(number);if(!number)issues.push(`Linha ${line}: número do chamado ausente.`);else if(seen.has(normalizedNumber))issues.push(`Linha ${line}: chamado ${number} repetido no próprio arquivo.`);else seen.add(normalizedNumber);const branchNumber=String(raw.branchNumber||raw.branch||"").trim();const cnpj=String(raw.branchCnpj||"").trim();const branch=branches.find(item=>item.numeroFilial===branchNumber)||branches.find(item=>cnpj&&normalize(item.cnpj)===normalize(cnpj))||branches.find(item=>normalize(item.nome)===normalize(String(raw.branch||"")));const status=statuses.includes(raw.status as AppTicket["status"])?raw.status as AppTicket["status"]:"Novo";const urgency=urgencies.includes(raw.urgency as AppTicket["urgency"])?raw.urgency as AppTicket["urgency"]:"Média";const analyst=String(raw.analistaResponsavel||"")||undefined;const tech=String(raw.tech||"")||undefined;const date=String(raw.date||"")||undefined;return {id:Date.now()+index,number:number||`#REVISAR-${line}`,branch:branch?.nome||String(raw.branch||"Filial não localizada"),branchId:branch?.id,branchNumber:branch?.numeroFilial||branchNumber||undefined,branchCnpj:branch?.cnpj||cnpj||undefined,city:branch?`${branch.cidade}, ${branch.uf}`:String(raw.city||"Cidade não informada"),uf:branch?.uf,address:branch?.endereco||"Endereço não informado",latitude:branch?.latitude??null,longitude:branch?.longitude??null,desc:String(raw.desc||"Sem descrição"),status,urgency,tech,date,duration:Number(raw.duration)||60,openedAt:String(raw.openedAt||"")||undefined,dueAt:String(raw.dueAt||"")||undefined,analyst,analistaResponsavel:analyst,dataAtribuicaoAnalista:analyst?new Date().toISOString():undefined,notes:String(raw.notes||"")||undefined,planningStatus:tech&&date?"em_rota_rascunho":"nao_planejado",reviewBranch:!branch} satisfies AppTicket});setPreview(parsed);setErrors(issues)};
 const existing=preview.filter(incoming=>tickets.some(ticket=>normalize(ticket.number)===normalize(incoming.number))).length;const fresh=preview.length-existing;
 const importNow=()=>{if(errors.length){flash("Corrija os erros do CSV antes de importar");return}setTickets(current=>{let next=[...current];preview.forEach(incoming=>{const index=next.findIndex(ticket=>normalize(ticket.number)===normalize(incoming.number));if(index<0){let id=incoming.id;while(next.some(ticket=>ticket.id===id))id++;next.push({...incoming,id})}else{const old=next[index];next[index]={...old,...incoming,id:old.id,tech:old.tech,date:old.date,routeOrder:old.routeOrder,routeId:old.routeId,planningStatus:old.planningStatus,duration:old.duration,notes:old.notes,latitude:isValidCoordinate(incoming.latitude,incoming.longitude)?incoming.latitude:old.latitude,longitude:isValidCoordinate(incoming.latitude,incoming.longitude)?incoming.longitude:old.longitude,branchId:incoming.branchId||old.branchId,branchNumber:incoming.branchNumber||old.branchNumber,branchCnpj:incoming.branchCnpj||old.branchCnpj}}});return next});flash(`${preview.length} chamados importados com sucesso`);setPreview([]);setFileName("");setErrors([]);if(input.current)input.current.value=""};
 const downloadModel=()=>{const content="numeroChamado;filial;cidade;descricao;status;urgencia;tecnicoPlanejado;dataPlanejada;tempoEstimado;dataAbertura;dataLimite;analista;observacoes\n#5001;01;Jaraguá do Sul;Descrição do chamado;Novo;Alta;;;60;;;;";const url=URL.createObjectURL(new Blob(["\uFEFF"+content],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="modelo-importacao-rotasmart.csv";link.click();URL.revokeObjectURL(url)};
 return <><div className="pagehead"><div><h1>Importar chamados</h1><p>Valide um CSV antes de atualizar a operação.</p></div><div className="page-actions"><button className="btn secondary" onClick={downloadModel}><Download size={17}/>Baixar modelo CSV</button></div></div><div className="import-grid"><div className="panel import-main"><div className="step"><span>1</span><div><h3>Envie seu arquivo</h3><p>CSV com até 10 MB. Nenhum dado é alterado antes da confirmação.</p></div></div><input ref={input} hidden type="file" accept=".csv,text/csv" onChange={event=>readFile(event.target.files?.[0])}/><div className={`dropzone ${fileName?"has-file":""}`} onClick={()=>input.current?.click()}>{fileName?<><div className="file-icon"><FileSpreadsheet/></div><div><b>{fileName}</b><span>{preview.length} registros encontrados</span></div>{!errors.length&&<Check className="file-check"/>}</>:<><div className="upload-icon"><UploadCloud/></div><b>Clique para selecionar um CSV</b><span>O arquivo será analisado antes da importação.</span></>}</div>{errors.map(error=><p className="warning-text" key={error}><AlertTriangle size={15}/>{error}</p>)}{fileName&&preview.length>0&&<><div className="step second"><span>2</span><div><h3>Prévia da importação</h3><p>{errors.length?"Existem erros bloqueando a importação.":"Arquivo válido para importação."}</p></div></div><div className="import-summary"><div><Sparkles/><b>{fresh}</b><span>Novos chamados</span></div><div><Download/><b>{existing}</b><span>Serão atualizados</span></div><div><AlertTriangle/><b>{errors.length+preview.filter(item=>item.reviewBranch).length}</b><span>Para revisar</span></div></div><button className="btn primary import-button" disabled={!preview.length||errors.length>0} onClick={importNow}><UploadCloud size={17}/>Importar {preview.length} chamados</button></>}</div><div className="panel rules"><h3>Regras de segurança</h3><div className="rule"><span>1</span><div><b>Duplicados normalizados</b><p>Espaços, acentos e pontuação não criam um segundo chamado.</p></div></div><div className="rule"><span>2</span><div><b>Coordenadas protegidas</b><p>Uma filial não reconhecida não apaga coordenadas já válidas.</p></div></div><div className="rule"><span>3</span><div><b>Planejamento preservado</b><p>Técnico, data, rota, ordem, duração e notas locais são mantidos em atualizações.</p></div></div></div></div></>;
}
