"use client";

import { useEffect, useMemo, useState } from "react";
import dynamic from "next/dynamic";
import {
  AlertTriangle, ArrowDown, ArrowUp, BarChart3, Bell, Building2, CalendarDays,
  Check, ChevronDown, ChevronRight, CircleHelp, Clock3, Download, FileSpreadsheet,
  Filter, GripVertical, Headphones, LayoutDashboard, Lightbulb, ListFilter, Map,
  MapPin, Menu, MoreHorizontal, Plus, Route, Search, Settings, SlidersHorizontal,
  Sparkles, TicketCheck, Trash2, UploadCloud, UserRound, Users, Wrench, X
} from "lucide-react";
import { Filial, cidadesFiliais, filiais as filiaisBase } from "./data/filiais";
import { calculateRouteDistance, getValidRoutePoints, isValidCoordinate } from "./utils/distance";
import RouteErrorBoundary from "./components/RouteErrorBoundary";
import { AppDataProvider, useAppData } from "./data/AppDataContext";
import ImportTickets from "./components/ImportTickets";
const LeafletRouteMap=dynamic(()=>import("./components/LeafletRouteMap"),{ssr:false,loading:()=><div className="map-loading">Carregando mapa OpenStreetMap…</div>});

type Status = "Novo" | "Programado" | "Aguardando compra" | "Aguardando entrega" | "Em atendimento" | "Concluído" | "Fechado";
type Page = "Dashboard" | "Chamados" | "Planner semanal" | "Montar rota" | "Mapa de rotas" | "Filiais / Postos" | "Técnicos" | "Importar chamados";
type Ticket = { id: number; number: string; branch: string; branchId?:number; branchNumber?:string; city: string; address: string; latitude?:number|null; longitude?:number|null; desc: string; status: Status; urgency: "Alta" | "Média" | "Baixa"; tech?: string; date?: string; duration: number; analyst?:string; openedAt?:string; dueAt?:string; notes?:string; routeOrder?:number; routeId?:string; planningStatus?:"nao_planejado"|"em_rota_rascunho"|"rota_confirmada"; reviewBranch?:boolean };
type Technician = { id:number; name:string; initials:string; color:string; city:string; address:string; startTime:string; endTime:string; active:boolean; notes:string; latitude?:number|null; longitude?:number|null };

const tickets: Ticket[] = [
  { id:1, number:"#4821", branch:filiaisBase[0].nome, city:`${filiaisBase[0].cidade}, ${filiaisBase[0].uf}`, desc:"Bomba 03 apresentando falha intermitente", status:"Novo", urgency:"Alta", duration:90, address:filiaisBase[0].endereco },
  { id:2, number:"#4818", branch:filiaisBase[4].nome, city:`${filiaisBase[4].cidade}, ${filiaisBase[4].uf}`, desc:"Preventiva do quadro elétrico", status:"Novo", urgency:"Média", duration:60, address:filiaisBase[4].endereco },
  { id:3, number:"#4812", branch:filiaisBase[5].nome, city:`${filiaisBase[5].cidade}, ${filiaisBase[5].uf}`, desc:"Ruído excessivo no compressor", status:"Programado", urgency:"Alta", tech:"Wagner", date:"17 Jul", duration:120, address:filiaisBase[5].endereco },
  { id:4, number:"#4809", branch:filiaisBase[10].nome, city:`${filiaisBase[10].cidade}, ${filiaisBase[10].uf}`, desc:"Troca do filtro da linha 02", status:"Programado", urgency:"Baixa", tech:"Vinícius", date:"18 Jul", duration:45, address:filiaisBase[10].endereco },
  { id:5, number:"#4805", branch:filiaisBase[9].nome, city:`${filiaisBase[9].cidade}, ${filiaisBase[9].uf}`, desc:"Substituição de placa controladora", status:"Aguardando compra", urgency:"Média", tech:"Valdemir", duration:80, address:filiaisBase[9].endereco },
  { id:6, number:"#4798", branch:filiaisBase[20].nome, city:`${filiaisBase[20].cidade}, ${filiaisBase[20].uf}`, desc:"Aguardando chegada do sensor", status:"Aguardando entrega", urgency:"Alta", tech:"Wagner", duration:100, address:filiaisBase[20].endereco },
  { id:7, number:"#4792", branch:filiaisBase[23].nome, city:`${filiaisBase[23].cidade}, ${filiaisBase[23].uf}`, desc:"Calibração do sistema de medição", status:"Em atendimento", urgency:"Média", tech:"Vinícius", date:"Hoje", duration:120, address:filiaisBase[23].endereco },
  { id:8, number:"#4788", branch:filiaisBase[25].nome, city:`${filiaisBase[25].cidade}, ${filiaisBase[25].uf}`, desc:"Manutenção preventiva concluída", status:"Concluído", urgency:"Baixa", tech:"Valdemir", date:"15 Jul", duration:60, address:filiaisBase[25].endereco },
  { id:9, number:"#4781", branch:filiaisBase[18].nome, city:`${filiaisBase[18].cidade}, ${filiaisBase[18].uf}`, desc:"Reparo no painel de controle", status:"Fechado", urgency:"Média", tech:"Wagner", date:"14 Jul", duration:90, address:filiaisBase[18].endereco },
];

const techs: Technician[] = [
  {id:1,name:"Wagner",initials:"WA",color:"#2563eb",city:"Jaraguá do Sul, SC",address:"Rua Manoel Francisco da Costa, 2010 — Jaraguá do Sul — SC",startTime:"06:00",endTime:"20:00",active:true,notes:""},
  {id:2,name:"Vinícius",initials:"VI",color:"#16a34a",city:"Jaraguá do Sul, SC",address:"Rua Manoel Francisco da Costa, 2010 — Jaraguá do Sul — SC",startTime:"06:00",endTime:"20:00",active:true,notes:""},
  {id:3,name:"Valdemir",initials:"VA",color:"#7c3aed",city:"Jaraguá do Sul, SC",address:"Rua Manoel Francisco da Costa, 2010 — Jaraguá do Sul — SC",startTime:"06:00",endTime:"20:00",active:true,notes:""},
];

const menu: {label:Page; icon:any}[] = [
  {label:"Dashboard",icon:LayoutDashboard},{label:"Chamados",icon:TicketCheck},{label:"Planner semanal",icon:CalendarDays},
  {label:"Montar rota",icon:Route},{label:"Mapa de rotas",icon:Map},{label:"Filiais / Postos",icon:Building2},
  {label:"Técnicos",icon:Users},{label:"Importar chamados",icon:UploadCloud},
];

export default function App(){return <AppDataProvider initialTickets={tickets} initialTechnicians={techs} initialBranches={filiaisBase}><AppShell/></AppDataProvider>}
function AppShell() {
  const [page,setPage]=useState<Page>("Dashboard");
  const [search,setSearch]=useState("");
  const {tickets:appTickets,setTickets:setAppTickets,clearLocalData}=useAppData();
  const [toast,setToast]=useState("");
  const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2600)};
  const openGlobalSearch=(value:string)=>{setSearch(value);if(value.trim())setPage("Chamados")};
  return <div className="app">
    <aside className="sidebar">
      <div className="brand"><div className="brandmark"><Route size={22}/></div><div><b>RotaSmart</b><span>MANUTENÇÃO</span></div></div>
      <nav>{menu.map(({label,icon:Icon})=><button key={label} className={page===label?"active":""} onClick={()=>setPage(label)}><Icon size={18}/><span>{label}</span>{label==="Chamados"&&<em>{appTickets.length}</em>}</button>)}</nav>
      <div className="side-bottom"><button><CircleHelp size={18}/>Central de ajuda</button><button onClick={clearLocalData}><Settings size={18}/>Limpar dados locais</button>
        <div className="profile"><div className="avatar">IC</div><div><b>Inácio Carvalho</b><span>Analista de operações</span></div><MoreHorizontal size={18}/></div>
      </div>
    </aside>
    <main>
      <header><div className="mobile-menu"><Menu/></div><div className="global-search"><Search size={18}/><input value={search} onChange={e=>openGlobalSearch(e.target.value)} placeholder="Buscar chamado, filial ou técnico..."/><kbd>⌘ K</kbd></div><div className="header-actions"><button><CircleHelp size={19}/></button><button className="notif"><Bell size={19}/><i/></button><div className="avatar small">IC</div></div></header>
      <section className="content">
        {page==="Dashboard"&&<Dashboard go={setPage}/>}
        {page==="Chamados"&&<Kanban items={appTickets} setItems={setAppTickets} initialSearch={search} flash={flash}/>}
        {page==="Planner semanal"&&<Planner items={appTickets} setItems={setAppTickets} go={setPage} flash={flash}/>}
        {page==="Montar rota"&&<RouteErrorBoundary><RouteBuilder flash={flash} items={appTickets} setItems={setAppTickets}/></RouteErrorBoundary>}
        {page==="Mapa de rotas"&&<RouteErrorBoundary><RouteMap flash={flash} items={appTickets}/></RouteErrorBoundary>}
        {page==="Filiais / Postos"&&<Branches flash={flash}/>}
        {page==="Técnicos"&&<Technicians flash={flash}/>}
        {page==="Importar chamados"&&<ImportTickets flash={flash}/>} 
      </section>
    </main>
    {toast&&<div className="toast"><Check size={17}/>{toast}</div>}
  </div>
}

function PageHead({eyebrow,title,sub,children}:{eyebrow?:string,title:string,sub:string,children?:React.ReactNode}){
 return <div className="pagehead"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{sub}</p></div><div className="page-actions">{children}</div></div>
}

function Dashboard({go}:{go:(p:Page)=>void}){
 const {tickets}=useAppData();
 const stats=[["Total de chamados","9","Todos os status",TicketCheck,"blue"],["Novos","2","+2 desde ontem",Sparkles,"cyan"],["Programados","2","Para esta semana",CalendarDays,"indigo"],["Aguardando compra","1","Requer atenção",Download,"amber"],["Aguardando entrega","1","Peça em trânsito",Clock3,"orange"],["Em atendimento","1","Agora",Wrench,"purple"],["Concluídos","1","Esta semana",TicketCheck,"green"],["Rotas planejadas","5","Semana atual",Route,"teal"]];
 return <><PageHead eyebrow="QUINTA-FEIRA, 16 DE JULHO" title="Visão geral" sub="Acompanhe a operação e tome decisões rápidas."><button className="btn secondary"><Download size={17}/>Exportar</button><button className="btn primary" onClick={()=>go("Montar rota")}><Plus size={17}/>Planejar rota</button></PageHead>
  <div className="stats">{stats.map(([a,b,c,I,color]:any)=><div className="stat" key={a}><div className={`stat-icon ${color}`}><I size={20}/></div><div className="stat-label">{a}</div><strong>{b}</strong><span>{c}</span></div>)}</div>
  <div className="dash-grid">
   <div className="panel wide"><PanelTitle title="Chamados por status" sub="Distribuição atual da operação" action="Ver chamados" onClick={()=>go("Chamados")}/><div className="bars">{[["Novo",2,"#0ea5e9"],["Programado",2,"#4f46e5"],["Aguard. compra",1,"#f59e0b"],["Aguard. entrega",1,"#f97316"],["Em atendimento",1,"#8b5cf6"],["Concluído",1,"#16a34a"],["Fechado",1,"#64748b"]].map(([n,v,c]:any)=><div className="bar-item" key={n}><div className="bar-shell"><div style={{height:`${v*36}%`,background:c}}><b>{v}</b></div></div><span>{n}</span></div>)}</div></div>
   <div className="panel"><PanelTitle title="Rotas da semana" sub="Progresso planejado"/><div className="route-progress"><div className="donut"><div><b>5</b><span>rotas</span></div></div><div className="legend"><p><i className="dot green"/>Concluídas <b>2</b></p><p><i className="dot blue"/>Planejadas <b>2</b></p><p><i className="dot purple"/>Em andamento <b>1</b></p></div></div><button className="link-btn" onClick={()=>go("Planner semanal")}>Abrir planner semanal <ChevronRight size={16}/></button></div>
  </div>
  <div className="dash-grid bottom"><div className="panel wide"><PanelTitle title="Próximos atendimentos" sub="Chamados planejados para os próximos dias" action="Ver planner" onClick={()=>go("Planner semanal")}/><table><thead><tr><th>CHAMADO</th><th>FILIAL</th><th>TÉCNICO</th><th>DATA</th><th>URGÊNCIA</th></tr></thead><tbody>{tickets.filter(t=>t.tech).slice(0,4).map(t=><tr key={t.id}><td><b>{t.number}</b></td><td>{t.branch}<small>{t.city}</small></td><td><Avatar name={t.tech!}/>{t.tech}</td><td>{t.date||"A definir"}</td><td><Urgency value={t.urgency}/></td></tr>)}</tbody></table></div>
  <div className="panel"><PanelTitle title="Atenção necessária" sub="Itens que podem impactar a operação"/><div className="attention"><div className="warn-icon"><AlertTriangle/></div><div><b>Rota de Wagner pode melhorar</b><p>A rota de sexta tem 38 km de deslocamento extra.</p><button onClick={()=>go("Montar rota")}>Ver sugestão <ChevronRight size={15}/></button></div></div><div className="attention"><div className="wait-icon"><Clock3/></div><div><b>1 chamado próximo do prazo</b><p>O chamado #4798 vence amanhã às 14h.</p><button onClick={()=>go("Chamados")}>Ver chamado <ChevronRight size={15}/></button></div></div></div></div>
 </>;
}

function PanelTitle({title,sub,action,onClick}:{title:string,sub:string,action?:string,onClick?:()=>void}){return <div className="panel-title"><div><h3>{title}</h3><p>{sub}</p></div>{action&&<button onClick={onClick}>{action}<ChevronRight size={15}/></button>}</div>}
function Urgency({value}:{value:string}){return <span className={`pill urgency ${value.toLowerCase().replace("é","e")}`}><i/>{value}</span>}
function Avatar({name}:{name:string}){const {technicians}=useAppData();const t=technicians.find(x=>x.name===name);return <span className="tiny-avatar" style={{background:t?.color}}>{t?.initials||"?"}</span>}

function Kanban({items,setItems,initialSearch,flash}:{items:Ticket[];setItems:(x:Ticket[])=>void;initialSearch:string;flash:(s:string)=>void}){
 const {technicians:techs,branches:filiaisBase,createTicket}=useAppData();
 const cols:Status[]=["Novo","Programado","Aguardando compra","Aguardando entrega","Em atendimento","Concluído","Fechado"];
 const [query,setQuery]=useState(initialSearch); const [tech,setTech]=useState(""); const [urgency,setUrgency]=useState(""); const [status,setStatus]=useState(""); const [city,setCity]=useState(""); const [editing,setEditing]=useState<Ticket|null>(null); const [isNew,setIsNew]=useState(false);
 useEffect(()=>setQuery(initialSearch),[initialSearch]);
 const shown=items.filter(t=>{const hay=`${t.number} ${t.branch} ${t.branchNumber||""} ${t.city} ${t.desc} ${t.tech||""} ${t.status}`.toLowerCase();return(!query||hay.includes(query.toLowerCase()))&&(!tech||t.tech===tech)&&(!urgency||t.urgency===urgency)&&(!status||t.status===status)&&(!city||t.city===city)});
 const openNew=()=>{const f=filiaisBase[0];setEditing({id:0,number:"",branch:f?.nome||"Filial não localizada",branchId:f?.id,branchNumber:f?.numeroFilial,city:f?`${f.cidade}, ${f.uf}`:"Cidade não informada",address:f?.endereco||"Endereço não informado",latitude:f?.latitude??null,longitude:f?.longitude??null,desc:"",status:"Novo",urgency:"Média",duration:60,analyst:"",openedAt:new Date().toISOString().slice(0,10),tech:undefined,date:undefined,routeId:undefined,routeOrder:undefined,planningStatus:"nao_planejado",reviewBranch:!f});setIsNew(true)};
 const save=()=>{if(!editing||!editing.number.trim()||!editing.desc.trim())return;if(isNew){const {id:ignored,...draft}=editing;createTicket({...draft,number:draft.number.trim(),desc:draft.desc.trim(),status:draft.status||"Novo",urgency:draft.urgency||"Média",duration:Number.isFinite(draft.duration)&&draft.duration>0?draft.duration:60,tech:draft.tech||undefined,date:draft.date||undefined,routeId:undefined,routeOrder:undefined,planningStatus:"nao_planejado"})}else setItems(items.map(x=>x.id===editing.id?editing:x));setEditing(null);setIsNew(false);flash(isNew?"Chamado criado com sucesso":"Chamado atualizado com sucesso")};
 return <><PageHead title="Chamados" sub="Acompanhe e organize o fluxo de atendimentos."><button className="btn secondary"><ListFilter size={17}/>Filtros</button><button className="btn primary" onClick={openNew}><Plus size={17}/>Novo chamado</button></PageHead>
 <div className="toolbar kanban-filters"><div className="searchbox"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar chamados..."/></div><select className="select" value={tech} onChange={e=>setTech(e.target.value)}><option value="">Todos os técnicos</option>{techs.map(t=><option key={t.name}>{t.name}</option>)}</select><select className="select" value={urgency} onChange={e=>setUrgency(e.target.value)}><option value="">Urgências</option>{["Alta","Média","Baixa"].map(x=><option key={x}>{x}</option>)}</select><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Status</option>{cols.map(x=><option key={x}>{x}</option>)}</select><select className="select" value={city} onChange={e=>setCity(e.target.value)}><option value="">Cidades</option>{cidadesFiliais.map(x=><option key={x} value={`${x}, SC`}>{x}</option>)}</select><span className="result-count">{shown.length} chamados</span></div>
 <div className="kanban">{cols.map((s,i)=><div className="kanban-col" key={s}><div className="kanban-head"><span className={`status-dot s${i}`}/><b>{s}</b><em>{shown.filter(t=>t.status===s).length}</em><MoreHorizontal size={17}/></div>{shown.filter(t=>t.status===s).map(t=><div key={t.id} onClick={()=>{setEditing({...t});setIsNew(false)}}><TicketCard t={t}/></div>)}
 {i<2&&<button className="add-card" onClick={openNew}><Plus size={15}/>Adicionar chamado</button>}</div>)}</div>{editing&&<TicketModal ticket={editing} onChange={setEditing} onCancel={()=>setEditing(null)} onSave={save}/>}</>;
}
function TicketCard({t}:{t:Ticket}){return <div className="ticket-card"><div><b>{t.number}</b><Urgency value={t.urgency}/></div><h4>{t.desc}</h4><p><Building2 size={14}/>{t.branch}</p><p><MapPin size={14}/>{t.city}</p>{t.tech&&<div className="ticket-foot"><span><Avatar name={t.tech}/>{t.tech}</span><span><CalendarDays size={14}/>{t.date||"A definir"}</span></div>}</div>}
function TicketModal({ticket,onChange,onCancel,onSave}:{ticket:Ticket;onChange:(t:Ticket)=>void;onCancel:()=>void;onSave:()=>void}){
 const {technicians:techs,branches:filiaisBase}=useAppData();
 const set=(k:keyof Ticket,v:any)=>onChange({...ticket,[k]:v}); const selectBranch=(id:string)=>{const f=filiaisBase.find(x=>String(x.id)===id);if(f)onChange({...ticket,branch:f.nome,branchId:f.id,branchNumber:f.numeroFilial,city:`${f.cidade}, ${f.uf}`,address:f.endereco,latitude:f.latitude,longitude:f.longitude,reviewBranch:false});else onChange({...ticket,branchId:undefined,branchNumber:undefined,reviewBranch:true})};
 return <div className="modal-bg tech-modal-bg"><div className="tech-modal ticket-modal"><div className="tech-modal-head"><div><span className="eyebrow">CHAMADO</span><h2>{ticket.id?`Editar ${ticket.number}`:"Novo chamado"}</h2><p>Dados do atendimento e planejamento operacional.</p></div><button onClick={onCancel}><X/></button></div><div className="tech-form">
 <label className="field"><span>Número *</span><input value={ticket.number} onChange={e=>set("number",e.target.value)}/></label><label className="field"><span>Status</span><select value={ticket.status} onChange={e=>set("status",e.target.value)}>{["Novo","Programado","Aguardando compra","Aguardando entrega","Em atendimento","Concluído","Fechado"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label className="field span-2"><span>Filial</span><select value={filiaisBase.find(f=>f.numeroFilial===ticket.branchNumber)?.id||""} onChange={e=>selectBranch(e.target.value)}>{filiaisBase.map(f=><option key={f.id} value={f.id}>{f.numeroFilial} — {f.nome}</option>)}</select></label><label className="field"><span>Cidade</span><input value={ticket.city} readOnly/></label><label className="field"><span>Endereço</span><input value={ticket.address} readOnly/></label>
 <label className="field span-2"><span>Descrição *</span><textarea value={ticket.desc} onChange={e=>set("desc",e.target.value)}/></label><label className="field"><span>Urgência</span><select value={ticket.urgency} onChange={e=>set("urgency",e.target.value)}>{["Alta","Média","Baixa"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Analista</span><input value={ticket.analyst||""} onChange={e=>set("analyst",e.target.value)}/></label>
 <label className="field"><span>Técnico planejado</span><select value={ticket.tech||""} onChange={e=>set("tech",e.target.value)}><option value="">A definir</option>{techs.map(t=><option key={t.name}>{t.name}</option>)}</select></label><label className="field"><span>Data planejada</span><input type="date" value={ticket.date||""} onChange={e=>set("date",e.target.value)}/></label><label className="field"><span>Tempo estimado (min)</span><input type="number" value={ticket.duration} onChange={e=>set("duration",Number(e.target.value))}/></label><label className="field"><span>Data limite</span><input type="date" value={ticket.dueAt||""} onChange={e=>set("dueAt",e.target.value)}/></label><label className="field span-2"><span>Observações</span><textarea value={ticket.notes||""} onChange={e=>set("notes",e.target.value)}/></label>
 </div><div className="tech-modal-actions"><button className="btn secondary" onClick={onCancel}>Cancelar</button><button className="btn primary" onClick={onSave}><Check size={17}/>Salvar chamado</button></div></div></div>;
}

function Planner({items,setItems,go,flash}:{items:Ticket[];setItems:(x:Ticket[])=>void;go:(p:Page)=>void;flash:(s:string)=>void}){
 const {technicians:techs}=useAppData();
 const [offset,setOffset]=useState(0); const [planning,setPlanning]=useState<Ticket|null>(null);
 const monday=useMemo(()=>{const d=new Date();const day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1)+offset*7);d.setHours(12,0,0,0);return d},[offset]);
 const days=Array.from({length:6},(_,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);return d});
 const iso=(d:Date)=>d.toISOString().slice(0,10); const labels=["SEG","TER","QUA","QUI","SEX","SÁB"];
 const savePlan=()=>{if(!planning)return;const planned:Ticket={...planning,status:"Programado",routeId:planning.tech&&planning.date?`${planning.tech}-${planning.date}`:undefined,planningStatus:planning.planningStatus==="nao_planejado"?"nao_planejado":planning.planningStatus||"em_rota_rascunho"};setItems(items.map(x=>x.id===planning.id?planned:x));setPlanning(null);flash("Planejamento atualizado")};
 const removePlan=()=>{if(!planning)return;setItems(items.map(x=>x.id===planning.id?{...x,tech:undefined,date:undefined,routeOrder:undefined,routeId:undefined,planningStatus:"nao_planejado"}:x));setPlanning(null);flash("Chamado removido da rota")};
 return <><PageHead title="Planner semanal" sub="Visualize a agenda da equipe e distribua os chamados."><button className="btn secondary"><ChevronDown size={17}/>Esta semana</button><button className="btn primary" onClick={()=>{setPlanning(items.find(x=>!x.tech)||items[0])}}><Plus size={17}/>Planejar chamado</button></PageHead>
 <div className="week-nav"><button onClick={()=>setOffset(offset-1)}>‹</button><b>{days[0].toLocaleDateString("pt-BR",{day:"2-digit",month:"short"})} — {days[5].toLocaleDateString("pt-BR",{day:"2-digit",month:"short",year:"numeric"})}</b><button onClick={()=>setOffset(offset+1)}>›</button><button className="today" onClick={()=>setOffset(0)}>Hoje</button></div>
 <div className="planner panel"><div className="planner-row planner-head"><div>TÉCNICO</div>{days.map((d,i)=><div className={i===3?"today-col":""} key={iso(d)}><b>{labels[i]}</b><span>{d.getDate()}</span></div>)}</div>
 {techs.map(tech=><div className="planner-row" key={tech.name}><div className="tech-cell"><Avatar name={tech.name}/><span><b>{tech.name}</b><small>{items.filter(x=>x.tech===tech.name&&days.some(d=>x.date===iso(d))).length} chamados</small></span></div>{days.map((d,di)=><div className={di===3?"today-col day-cell":"day-cell"} key={iso(d)}>{items.filter(x=>x.tech===tech.name&&x.date===iso(d)).map(t=><button className="plan-card" style={{borderLeftColor:tech.color}} key={t.id} onClick={()=>setPlanning({...t})}><b>{t.number}</b><span>{t.city.split(",")[0]}</span><small><Clock3 size={12}/>{t.duration} min · {t.planningStatus==="em_rota_rascunho"?"Rascunho":"Confirmada"}</small></button>)}<button className="slot-plus" onClick={()=>{const t=items.find(x=>!x.tech||!x.date);if(t)setPlanning({...t,tech:tech.name,date:iso(d)})}}><Plus size={15}/></button></div>)}</div>)}</div>{planning&&<PlanModal ticket={planning} onChange={setPlanning} onCancel={()=>setPlanning(null)} onSave={savePlan} onRemove={removePlan} go={go}/>}</>;
}
function PlanModal({ticket,onChange,onCancel,onSave,onRemove,go}:{ticket:Ticket;onChange:(t:Ticket)=>void;onCancel:()=>void;onSave:()=>void;onRemove:()=>void;go:(p:Page)=>void}){const {technicians:techs}=useAppData();return <div className="modal-bg"><div className="modal"><button className="modal-x" onClick={onCancel}><X/></button><h2>Editar planejamento</h2><p>{ticket.number} · {ticket.branch}</p><div className="tech-form"><label className="field"><span>Técnico</span><select value={ticket.tech||""} onChange={e=>onChange({...ticket,tech:e.target.value})}>{techs.map(t=><option key={t.name}>{t.name}</option>)}</select></label><label className="field"><span>Data planejada</span><input type="date" value={ticket.date||""} onChange={e=>onChange({...ticket,date:e.target.value})}/></label><label className="field"><span>Ordem na rota</span><input type="number" value={ticket.routeOrder||1} onChange={e=>onChange({...ticket,routeOrder:Number(e.target.value)})}/></label><label className="field"><span>Tempo estimado</span><input type="number" value={ticket.duration} onChange={e=>onChange({...ticket,duration:Number(e.target.value)})}/></label><label className="field span-2"><span>Status do planejamento</span><select value={ticket.planningStatus||"nao_planejado"} onChange={e=>onChange({...ticket,planningStatus:e.target.value as Ticket["planningStatus"]})}><option value="nao_planejado">Não planejado</option><option value="em_rota_rascunho">Em rota rascunho</option><option value="rota_confirmada">Rota confirmada</option></select></label></div><div className="modal-actions"><button className="btn secondary" onClick={onRemove}>Remover da rota</button><button className="btn secondary" onClick={onCancel}>Cancelar</button><button className="btn primary" onClick={onSave}>Salvar alterações</button></div></div></div>}

function RouteBuilder({flash,items,setItems}:{flash:(s:string)=>void;items:Ticket[];setItems:(x:Ticket[])=>void}){
 const {technicians:techs,branches:filiaisBase}=useAppData();
 const [tech,setTech]=useState("Wagner"); const [day,setDay]=useState(new Date().toISOString().slice(0,10));
 const [route,setRoute]=useState<Ticket[]>(()=>items.filter(t=>t.tech==="Wagner"&&t.date===new Date().toISOString().slice(0,10)).sort((a,b)=>(a.routeOrder||0)-(b.routeOrder||0)));
 const [suggest,setSuggest]=useState(false);
 const [query,setQuery]=useState(""); const [filter,setFilter]=useState<"all"|"high"|"region">("all");
 const [includePending,setIncludePending]=useState(false); const [showPlanned,setShowPlanned]=useState(false); const [showDrafts,setShowDrafts]=useState(false); const [optimized,setOptimized]=useState(false); const [manualInvalidated,setManualInvalidated]=useState(false);
 useEffect(()=>setRoute(items.filter(t=>t.tech===tech&&t.date===day&&t.planningStatus!=="nao_planejado").sort((a,b)=>(a.routeOrder||0)-(b.routeOrder||0))),[tech,day,items]);
 const available=items.filter(t=>!route.some(r=>r.id===t.id)&&!["Concluído","Fechado"].includes(t.status)&&(includePending||!["Aguardando compra","Aguardando entrega"].includes(t.status))&&((!t.planningStatus||t.planningStatus==="nao_planejado")||(t.planningStatus==="em_rota_rascunho"&&showDrafts)||(t.planningStatus==="rota_confirmada"&&showPlanned))&&(!query||`${t.number} ${t.branch} ${t.city}`.toLowerCase().includes(query.toLowerCase()))&&(filter!=="high"||t.urgency==="Alta")&&(filter!=="region"||t.city.includes("Jaraguá")));
 const markManual=()=>{if(optimized)setManualInvalidated(true);setOptimized(false)}; const move=(i:number,d:number)=>{const n=[...route]; const j=i+d;if(j<0||j>=n.length)return;[n[i],n[j]]=[n[j],n[i]];setRoute(n);markManual()};
 const removeFromRoute=(id:number)=>{setRoute(current=>current.filter(ticket=>ticket.id!==id));setItems(items.map(ticket=>ticket.id===id?{...ticket,tech:undefined,date:undefined,routeOrder:undefined,routeId:undefined,planningStatus:"nao_planejado"}:ticket));markManual();flash("Chamado removido da rota")};
 const routeId=`${tech}-${day}`;
 const persistRoute=(planningStatus:Ticket["planningStatus"])=>setItems(items.map(t=>{const i=route.findIndex(x=>x.id===t.id);if(i>=0)return {...t,status:planningStatus==="rota_confirmada"?"Programado":t.status,tech,date:day,routeOrder:i+1,routeId,planningStatus};if(t.routeId===routeId)return {...t,tech:undefined,date:undefined,routeOrder:undefined,routeId:undefined,planningStatus:"nao_planejado"};return t}));
 const saveDraft=()=>{persistRoute("em_rota_rascunho");flash("Rascunho salvo")};
 const confirm=()=>{persistRoute("rota_confirmada");flash("Rota confirmada com sucesso.")};
 const currentTech=techs.find(t=>t.name===tech)||techs[0];
 const routeFiliais=route.map(t=>filiaisBase.find(f=>f.numeroFilial===t.branchNumber)).filter(Boolean) as Filial[];
 const fallbackStart=filiaisBase.find(f=>f.cidade.toLowerCase().includes("jaragu")&&isValidCoordinate(f.latitude,f.longitude)); const startFilial=isValidCoordinate(currentTech.latitude,currentTech.longitude)?{latitude:currentTech.latitude!,longitude:currentTech.longitude!}:fallbackStart;
 const distance=calculateRouteDistance([...(startFilial?[startFilial]:[]),...routeFiliais]);
 return <><PageHead title="Montar rota" sub="Organize os atendimentos e mantenha o controle da operação."><button className="btn secondary" onClick={saveDraft}>Salvar rascunho</button><button className="btn primary" onClick={confirm}><Check size={17}/>Confirmar rota</button></PageHead>
 <div className="route-config panel"><label>Técnico <select className="select" value={tech} onChange={e=>setTech(e.target.value)}>{techs.map(t=><option key={t.name}>{t.name}</option>)}</select></label><label>Dia da rota <input className="select" type="date" value={day} onChange={e=>setDay(e.target.value)}/></label><div className="tech-hours"><Clock3 size={17}/><span>Jornada padrão<b>{currentTech.startTime} — {currentTech.endTime}</b></span></div></div>
 <div className="route-layout">
  <div className="panel available"><PanelTitle title="Chamados disponíveis" sub={`${available.length} chamados para planejar`}/><div className="mini-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por número, filial ou cidade..."/></div><div className="filter-chips"><button onClick={()=>setFilter("all")}>Todos <b>{available.length}</b></button><button onClick={()=>setFilter("high")}>Alta urgência</button><button onClick={()=>setFilter("region")}>Na região</button></div><div className="route-toggles"><label><input type="checkbox" checked={showDrafts} onChange={e=>setShowDrafts(e.target.checked)}/> Mostrar rascunhos</label><label><input type="checkbox" checked={showPlanned} onChange={e=>setShowPlanned(e.target.checked)}/> Mostrar já planejados</label><label><input type="checkbox" checked={includePending} onChange={e=>setIncludePending(e.target.checked)}/> Incluir pendentes</label></div>{available.map(t=><div className="available-ticket" key={t.id}><div><b>{t.number}</b><Urgency value={t.urgency}/></div><h4>{t.branch}</h4><p><MapPin size={13}/>{t.city}</p><small><Clock3 size={13}/>{t.duration} min</small><button onClick={()=>{setRoute([...route,t]);markManual()}}><Plus size={16}/></button></div>)}</div>
  <div className="panel route-order"><div className="route-title"><div><h3>Ordem da rota</h3><p>Arraste ou use as setas para reordenar.</p></div><span>{route.length} paradas</span></div><div className="route-start"><div className="start-pin"><MapPin/></div><div><b>Ponto de saída</b><span>Rua Manoel Francisco da Costa, 2010 — Jaraguá do Sul</span></div><button>Alterar</button></div>
   <div className="route-line">{route.map((t,i)=><div className="route-stop" key={t.id}><GripVertical size={18}/><div className="stop-num">{i+1}</div><div className="stop-info"><div><b>{t.number} · {t.branch}</b><Urgency value={t.urgency}/></div><p>{t.address} — {t.city}</p><small><Clock3 size={13}/>{t.duration} min de atendimento</small></div><div className="stop-actions"><button onClick={()=>move(i,-1)}><ArrowUp size={15}/></button><button onClick={()=>move(i,1)}><ArrowDown size={15}/></button><button onClick={()=>removeFromRoute(t.id)}><Trash2 size={15}/></button></div></div>)}</div>
   <button className="suggest-btn" onClick={()=>setSuggest(true)} disabled={!route.length}><Lightbulb size={19}/><span><b>{manualInvalidated?"Recalcular sugestão":optimized?"Rota atual otimizada":"Gerar rota sugerida"}</b><small>Ordena por cidade, urgência e tempo estimado.</small></span><ChevronRight/></button>
  </div>
  <div className="panel route-summary"><h3>Resumo da rota</h3><div className="summary-tech"><Avatar name={tech}/><div><b>{tech}</b><span>{new Date(`${day}T12:00`).toLocaleDateString("pt-BR")}</span></div></div><div className="summary-grid"><div><span>Chamados</span><b>{route.length}</b></div><div><span>Cidades</span><b>{new Set(route.map(x=>x.city)).size}</b></div><div><span>Atendimento</span><b>{Math.floor(route.reduce((a,x)=>a+x.duration,0)/60)}h {route.reduce((a,x)=>a+x.duration,0)%60}min</b></div><div><span>Distância aproximada</span><b>{distance===null?"Não calculada":`${distance.toFixed(1)} km`}</b></div><div><span>Deslocamento</span><b>{distance===null?"Não calculado":`${Math.round(distance)} min`}</b></div><div><span>Sem coordenadas</span><b>{route.length-routeFiliais.filter(f=>isValidCoordinate(f.latitude,f.longitude)).length}</b></div></div><div className={`alert-box ${optimized?"success-alert":""}`}><AlertTriangle size={19}/><div><b>{manualInvalidated?"Rota alterada manualmente.":optimized?"Rota mais eficiente aplicada.":route.length?"Análise da rota":"Rota vazia."}</b><p>{manualInvalidated?"Recalcule a sugestão para verificar eficiência.":route.length?`${new Set(route.map(x=>x.city)).size>1?`Rota espalhada: chamados em ${new Set(route.map(x=>x.city)).size} cidades. `:""}${distance===null?"Distância não calculada: há filiais sem coordenadas.":distance>180?"Rota longa: distância acima de 180 km.":"Distância aproximada disponível."}${route.reduce((sum,item)=>sum+item.duration,0)>480?" Rota pesada: atendimento estimado acima de 8h.":""}`:"Adicione chamados para iniciar o planejamento."}</p></div></div><div className="city-list"><b>Cidades envolvidas</b>{Array.from(new Set(route.map(x=>x.city))).map(c=><span key={c}><MapPin size={13}/>{c}</span>)}</div></div>
 </div>{suggest&&<Suggestion close={()=>setSuggest(false)} apply={()=>{const rank:Record<string,number>={"Alta":0,"Média":1,"Baixa":2};setRoute([...route].sort((a,b)=>a.city.localeCompare(b.city)||rank[a.urgency]-rank[b.urgency]||a.duration-b.duration));setOptimized(true);setManualInvalidated(false);setSuggest(false);flash("Rota mais eficiente aplicada.")}}/>}</>;
}
function Suggestion({close,apply}:{close:()=>void,apply:()=>void}){return <div className="modal-bg"><div className="modal suggestion-modal"><button className="modal-x" onClick={close}><X/></button><div className="bulb"><Lightbulb/></div><span className="eyebrow">INSIGHT ROTASMART</span><h2>Sugestão por cidade e prioridade</h2><p>Como as filiais ainda não possuem coordenadas, a ordem considera cidade/região e urgência. Nenhum cálculo real de mapa foi simulado.</p><div className="saving"><div><span>Economia estimada</span><b>Não calculada</b><small>Coordenadas pendentes</small></div><div><span>Critério aplicado</span><b>Região</b><small>Cidade + prioridade</small></div></div><div className="order-compare"><div className="suggest-order"><b>Ordem atual</b>{["#4812 · Joinville","#4821 · Jaraguá do Sul","#4818 · Brusque"].map((x,i)=><div key={x}><span>{i+1}</span>{x}</div>)}</div><div className="suggest-order"><b>Ordem sugerida</b>{["#4821 · Jaraguá do Sul","#4812 · Joinville","#4818 · Brusque"].map((x,i)=><div key={x}><span>{i+1}</span>{x}</div>)}</div></div><div className="api-note"><Sparkles size={16}/>Futura integração preparada para Leaflet/OpenStreetMap ou Google Routes API.</div><div className="modal-actions"><button className="btn secondary" onClick={close}>Cancelar</button><button className="btn primary" onClick={apply}><Check size={17}/>Aplicar sugestão</button></div></div></div>}

function RouteMap({flash,items}:{flash:(s:string)=>void;items:Ticket[]}){
 const {technicians:techs,branches:filiaisBase}=useAppData();
 const [selected,setSelected]=useState<number|null>(0); const [day,setDay]=useState(new Date().toISOString().slice(0,10)); const tech=selected===null?null:techs[selected];
 const dayItems=items.filter(t=>t.date===day&&t.tech&&t.planningStatus&&t.planningStatus!=="nao_planejado"); const assigned=tech?dayItems.filter(t=>t.tech===tech.name):dayItems;
 const baseCandidate=filiaisBase.find(f=>String(f.cidade||"").toLowerCase().includes("jaragu")); const base=baseCandidate&&isValidCoordinate(baseCandidate.latitude,baseCandidate.longitude)?baseCandidate:undefined;
 const visibleTechs=tech?[tech]:techs;
 const routes=visibleTechs.map(t=>({technician:t.name,color:t.color,start:{description:t.address,latitude:isValidCoordinate(t.latitude,t.longitude)?t.latitude:baseCandidate?.latitude??null,longitude:isValidCoordinate(t.latitude,t.longitude)?t.longitude:baseCandidate?.longitude??null},stops:dayItems.filter(x=>x.tech===t.name).map((x,index)=>{const f=filiaisBase.find(b=>b.numeroFilial===x.branchNumber);return isValidCoordinate(f?.latitude,f?.longitude)?{id:x.id??`stop-${index}`,number:x.number||"Chamado sem número",branch:f?.nome||x.branch||"Filial não associada",city:f?`${f.cidade}, ${f.uf}`:x.city||"Cidade não informada",address:f?.endereco||x.address||"Endereço não informado",technician:t.name,status:x.status||"Não informado",order:x.routeOrder||index+1,urgency:x.urgency||"Não informada",latitude:f!.latitude,longitude:f!.longitude}:null}).filter((stop):stop is NonNullable<typeof stop>=>stop!==null)}));
 const points=getValidRoutePoints([...(base?[base]:[]),...assigned.map(x=>filiaisBase.find(f=>f.numeroFilial===x.branchNumber)).filter((f):f is Filial=>!!f)]);
 const distance=calculateRouteDistance(points); const missing=assigned.filter(x=>{const f=filiaisBase.find(b=>b.numeroFilial===x.branchNumber);return !f||!isValidCoordinate(f.latitude,f.longitude)});
 return <><PageHead title="Mapa de rotas" sub="Visualize a distribuição dos atendimentos planejados."><input className="select" type="date" value={day} onChange={e=>setDay(e.target.value)}/><button className="btn primary" onClick={()=>{setSelected(null);flash("Exibindo todas as rotas do dia")}}><Route size={17}/>Ver todas as rotas</button></PageHead><div className="simulation-note"><Sparkles size={15}/>Mapa com coordenadas reais. A rota desenhada ainda é aproximação visual até integração com API de rotas.</div><div className="map-layout"><div className="map-side panel"><h3>Rotas do dia</h3><p>3 técnicos · {dayItems.length} chamados</p>{techs.map((t,i)=><button className={`map-tech ${selected===i?"selected":""}`} key={t.name} onClick={()=>setSelected(i)}><div className="map-tech-top"><Avatar name={t.name}/><div><b>{t.name}</b><span>{dayItems.filter(x=>x.tech===t.name).length} chamados</span></div><i style={{background:t.color}}/></div></button>)}<div className="map-detail"><b>{tech?.name||"Todas as rotas"} · {new Date(`${day}T12:00`).toLocaleDateString("pt-BR")}</b>{tech&&<span><MapPin size={13}/>{tech.address}</span>}<span><TicketCheck size={13}/>{assigned.length} chamados do dia</span><span><Building2 size={13}/>{Array.from(new Set(assigned.map(t=>t.city))).join(", ")||"Sem cidades planejadas"}</span><span><Route size={13}/>{distance===null?"Distância parcial/não calculada":`${distance.toFixed(1)} km · ${Math.round(distance)} min`}</span>{missing.length>0&&<b>Chamados sem coordenadas</b>}<span className="warning-text"><AlertTriangle size={13}/>{missing.length} filiais sem coordenadas</span>{missing.map(x=><span key={x.id} className="missing-stop">Sem coordenadas: {x.number} · {x.branch}</span>)}</div></div><LeafletRouteMap routes={routes}/></div></>;
}

const emptyFilial:Filial={id:0,numeroFilial:"",nome:"",cidade:"",uf:"SC",endereco:"",bairro:"",cep:"",cnpj:"",inscricaoEstadual:"",telefone:"",status:"ativo",latitude:null,longitude:null,geocodeStatus:"pendente",statusDados:"incompleto",fonteCoordenada:"",linkMapa:"",observacoes:""};
function Branches({flash}:{flash:(s:string)=>void}){
 const {branches:items,setBranches:setItems,setTickets}=useAppData();
 const [editing,setEditing]=useState<Filial|null>(null);
 const [isNew,setIsNew]=useState(false);
 const [query,setQuery]=useState(""); const [city,setCity]=useState(""); const [status,setStatus]=useState(""); const [issue,setIssue]=useState("");
 const cities=useMemo(()=>Array.from(new Set(items.map(f=>f.cidade).filter(Boolean))).sort(),[items]);
 const shown=items.filter(f=>(!query||`${f.numeroFilial} ${f.nome} ${f.cidade}`.toLowerCase().includes(query.toLowerCase()))&&(!city||f.cidade===city)&&(!status||f.status===status)&&(!issue||(issue==="coords"?f.latitude===null||f.longitude===null:f.statusDados==="incompleto")));
 const save=()=>{if(!editing||!editing.nome.trim())return;const hasCoords=isValidCoordinate(editing.latitude,editing.longitude);const clean:Filial={...editing,statusDados:(!editing.cidade||!editing.endereco||!editing.cep)?"incompleto":hasCoords?"ok":"sem_coordenadas",geocodeStatus:hasCoords?"preenchida":"pendente"};setItems(isNew?[...items,{...clean,id:Math.max(0,...items.map(x=>x.id))+1}]:items.map(x=>x.id===clean.id?clean:x));setTickets(current=>current.map(ticket=>ticket.branchNumber===clean.numeroFilial?{...ticket,branch:clean.nome,city:`${clean.cidade}, ${clean.uf}`,address:clean.endereco}:ticket));setEditing(null);flash(isNew?"Nova filial cadastrada com sucesso":"Filial atualizada com sucesso")};
 return <><PageHead title="Filiais e postos" sub="Base real extraída do documento Agrícola."><button className="btn secondary"><Download size={17}/>Exportar</button><button className="btn primary" onClick={()=>{setEditing({...emptyFilial});setIsNew(true)}}><Plus size={17}/>Nova filial</button></PageHead>
 <div className="toolbar branch-filters"><div className="searchbox"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar filial..."/></div><select className="select" value={city} onChange={e=>setCity(e.target.value)}><option value="">Todas as cidades</option>{cities.map(c=><option key={c}>{c}</option>)}</select><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option><option value="ativo">Ativos</option><option value="desativado">Desativados</option></select><select className="select" value={issue} onChange={e=>setIssue(e.target.value)}><option value="">Todos os dados</option><option value="incomplete">Dados incompletos</option><option value="coords">Sem coordenadas</option></select><span className="result-count">{shown.length} filiais</span></div>
 <div className="panel table-panel"><table><thead><tr><th>Nº FILIAL</th><th>NOME</th><th>LOCALIZAÇÃO</th><th>ENDEREÇO</th><th>STATUS / DADOS</th><th></th></tr></thead><tbody>{shown.map(f=><tr key={f.id}><td><b>{f.numeroFilial}</b></td><td><b>{f.nome}</b><small>{f.cnpj}</small></td><td>{f.cidade||"Não informada"}<small>{f.uf}</small></td><td>{f.endereco||"Não informado"}<small>{f.cep}</small></td><td><span className={`active-pill ${f.status==="ativo"?"":"off"}`}><i/>{f.status==="ativo"?"Ativo":"Desativado"}</span>{f.geocodeStatus==="pendente"&&<span className="data-warning">Sem coordenadas</span>}{f.statusDados==="incompleto"&&<span className="data-warning danger">Dados incompletos</span>}</td><td><button className="icon-button" onClick={()=>{setEditing({...f});setIsNew(false)}}><MoreHorizontal/></button></td></tr>)}</tbody></table></div>
 {editing&&<FilialModal filial={editing} isNew={isNew} onChange={setEditing} onCancel={()=>setEditing(null)} onSave={save}/>}</>;
}

function FilialModal({filial,isNew,onChange,onCancel,onSave}:{filial:Filial;isNew:boolean;onChange:(f:Filial)=>void;onCancel:()=>void;onSave:()=>void}){
 const set=(key:keyof Filial,value:any)=>onChange({...filial,[key]:value});
 return <div className="modal-bg tech-modal-bg"><div className="tech-modal branch-modal"><div className="tech-modal-head"><div><span className="eyebrow">{isNew?"NOVO CADASTRO":"EDITAR FILIAL"}</span><h2>{isNew?"Nova filial":filial.nome}</h2><p>Dados operacionais da base de filiais e postos.</p></div><button onClick={onCancel}><X/></button></div><div className="tech-form">
 <label className="field"><span>Número da filial</span><input value={filial.numeroFilial} onChange={e=>set("numeroFilial",e.target.value)}/></label><label className="field"><span>Status</span><select value={filial.status} onChange={e=>set("status",e.target.value)}><option value="ativo">Ativo</option><option value="desativado">Desativado</option></select></label>
 <label className="field span-2"><span>Nome *</span><input value={filial.nome} onChange={e=>set("nome",e.target.value)}/></label><label className="field"><span>Cidade</span><input list="real-cities" value={filial.cidade} onChange={e=>set("cidade",e.target.value)}/><datalist id="real-cities">{cidadesFiliais.map(c=><option key={c}>{c}</option>)}</datalist></label><label className="field"><span>UF</span><input maxLength={2} value={filial.uf} onChange={e=>set("uf",e.target.value.toUpperCase())}/></label>
 <label className="field span-2"><span>Endereço</span><input value={filial.endereco} onChange={e=>set("endereco",e.target.value)}/></label><label className="field"><span>CEP</span><input value={filial.cep} onChange={e=>set("cep",e.target.value)}/></label><label className="field"><span>Telefone</span><input value={filial.telefone} onChange={e=>set("telefone",e.target.value)}/></label><label className="field span-2"><span>CNPJ</span><input value={filial.cnpj} onChange={e=>set("cnpj",e.target.value)}/></label>
 <label className="field"><span>Latitude</span><input type="number" step="any" value={filial.latitude??""} onChange={e=>set("latitude",e.target.value===""?null:Number(e.target.value))}/></label><label className="field"><span>Longitude</span><input type="number" step="any" value={filial.longitude??""} onChange={e=>set("longitude",e.target.value===""?null:Number(e.target.value))}/></label><label className="field span-2"><span>Observações</span><textarea value={filial.observacoes} onChange={e=>set("observacoes",e.target.value)}/></label></div><div className="tech-modal-actions"><button className="btn secondary" onClick={onCancel}>Cancelar</button><button className="btn primary" disabled={!filial.nome.trim()} onClick={onSave}><Check size={17}/>Salvar alterações</button></div></div></div>;
}
function DataToolbar({count}:{count:string}){return <div className="toolbar"><div className="searchbox"><Search size={17}/><input placeholder="Buscar por nome, cidade ou número..."/></div><button className="select"><Filter size={16}/>Todos os status<ChevronDown size={16}/></button><span className="result-count">{count}</span></div>}
const emptyTechnician: Technician = {id:0,name:"",initials:"",color:"#2563eb",city:"",address:"",startTime:"08:00",endTime:"17:30",active:true,notes:"",latitude:null,longitude:null};

function Technicians({flash}:{flash:(s:string)=>void}){
 const {technicians:items,setTechnicians:setItems,setTickets}=useAppData();
 const [editing,setEditing]=useState<Technician|null>(null);
 const [isNew,setIsNew]=useState(false);
 const openNew=()=>{setEditing({...emptyTechnician});setIsNew(true)};
 const openEdit=(tech:Technician)=>{setEditing({...tech});setIsNew(false)};
 const save=()=>{
  if(!editing||!editing.name.trim())return;
  if(isNew){
   const created={...editing,id:Math.max(0,...items.map(t=>t.id))+1,initials:editing.initials.trim().toUpperCase()||editing.name.slice(0,2).toUpperCase()};
   setItems([...items,created]); flash("Novo técnico cadastrado com sucesso");
  }else{
   const previousName=items.find(t=>t.id===editing.id)?.name;
   setItems(items.map(t=>t.id===editing.id?{...editing,initials:editing.initials.trim().toUpperCase()}:t)); flash("Alterações salvas com sucesso");
   if(previousName&&previousName!==editing.name)setTickets(current=>current.map(ticket=>ticket.tech===previousName?{...ticket,tech:editing.name}:ticket));
  }
  setEditing(null);
 };
 return <><PageHead title="Técnicos" sub="Configure a equipe, jornadas e pontos de saída."><button className="btn primary" onClick={openNew}><Plus size={17}/>Novo técnico</button></PageHead>
 <div className="tech-cards">{items.map(t=><div className="panel tech-detail" key={t.id}><div className="tech-card-head"><div className="big-avatar" style={{background:t.color}}>{t.initials}</div><div><h3>{t.name}</h3><span className={`active-pill ${t.active?"":"off"}`}><i/>{t.active?"Ativo":"Inativo"}</span></div><button aria-label={`Editar ${t.name}`} onClick={()=>openEdit(t)}><MoreHorizontal/></button></div><div className="tech-data"><p><MapPin/><span>Cidade base<b>{t.city||"Não informada"}</b></span></p><p><Route/><span>Ponto de saída padrão<b>{t.address||"Não informado"}</b></span></p><p><Clock3/><span>Jornada padrão<b>{t.startTime} — {t.endTime}</b></span></p></div><div className="map-color"><span>Cor no mapa</span><i style={{background:t.color}}/><code>{t.color}</code></div><button className="edit-tech" onClick={()=>openEdit(t)}>Editar técnico</button></div>)}</div>
 {editing&&<TechnicianModal technician={editing} isNew={isNew} onChange={setEditing} onCancel={()=>setEditing(null)} onSave={save}/>}</>;
}

function TechnicianModal({technician,isNew,onChange,onCancel,onSave}:{technician:Technician;isNew:boolean;onChange:(t:Technician)=>void;onCancel:()=>void;onSave:()=>void}){
 const update=<K extends keyof Technician>(key:K,value:Technician[K])=>onChange({...technician,[key]:value});
 return <div className="modal-bg tech-modal-bg" role="dialog" aria-modal="true" aria-labelledby="tech-modal-title"><div className="tech-modal">
  <div className="tech-modal-head"><div><span className="eyebrow">{isNew?"NOVO CADASTRO":"EDITAR CADASTRO"}</span><h2 id="tech-modal-title">{isNew?"Novo técnico":`Editar ${technician.name}`}</h2><p>Configure os dados operacionais e a identificação no mapa.</p></div><button onClick={onCancel} aria-label="Fechar"><X/></button></div>
  <div className="tech-form">
   <label className="field span-2"><span>Nome *</span><input autoFocus value={technician.name} onChange={e=>update("name",e.target.value)} placeholder="Nome completo"/></label>
   <label className="field"><span>Sigla / iniciais</span><input maxLength={3} value={technician.initials} onChange={e=>update("initials",e.target.value.toUpperCase())} placeholder="Ex.: WA"/></label>
   <label className="field"><span>Status</span><select value={technician.active?"active":"inactive"} onChange={e=>update("active",e.target.value==="active")}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></label>
   <label className="field span-2"><span>Cidade base</span><input value={technician.city} onChange={e=>update("city",e.target.value)} placeholder="Cidade, UF"/></label>
   <label className="field span-2"><span>Ponto de saída padrão</span><input value={technician.address} onChange={e=>update("address",e.target.value)} placeholder="Endereço completo"/></label>
   <label className="field"><span>Latitude do ponto de saída</span><input type="number" step="any" value={technician.latitude??""} onChange={e=>update("latitude",e.target.value===""?null:Number(e.target.value))}/></label>
   <label className="field"><span>Longitude do ponto de saída</span><input type="number" step="any" value={technician.longitude??""} onChange={e=>update("longitude",e.target.value===""?null:Number(e.target.value))}/></label>
   <label className="field"><span>Horário inicial padrão</span><input type="time" value={technician.startTime} onChange={e=>update("startTime",e.target.value)}/></label>
   <label className="field"><span>Horário final padrão</span><input type="time" value={technician.endTime} onChange={e=>update("endTime",e.target.value)}/></label>
   <label className="field span-2"><span>Cor no mapa</span><div className="color-field"><input type="color" value={technician.color} onChange={e=>update("color",e.target.value)}/><input value={technician.color} onChange={e=>update("color",e.target.value)} maxLength={7}/><i style={{background:technician.color}}/></div></label>
   <label className="field span-2"><span>Observações</span><textarea rows={3} value={technician.notes} onChange={e=>update("notes",e.target.value)} placeholder="Informações internas sobre disponibilidade, região ou especialidade."/></label>
  </div>
  <div className="tech-modal-actions"><button className="btn secondary" onClick={onCancel}>Cancelar</button><button className="btn primary" disabled={!technician.name.trim()} onClick={onSave}><Check size={17}/>Salvar alterações</button></div>
 </div></div>;
}
