export type AppRole = "admin" | "analista" | "visualizador";
export type DataMode = "local" | "cloud";

export type AnalystRow = { id:string;name:string;email:string|null;phone:string|null;department:string|null;initials:string|null;color:string|null;notes:string|null;active:boolean;created_at:string;updated_at:string };
export type TechnicianRow = { id:string;name:string;email:string|null;phone:string|null;color:string|null;active:boolean;start_latitude:number|null;start_longitude:number|null;start_address:string|null;start_city:string|null;start_uf:string|null;start_time:string|null;end_time:string|null;initials:string|null;notes:string|null;created_at:string;updated_at:string };
export type BranchRow = { id:string;branch_number:string|null;name:string;cnpj:string|null;address:string|null;neighborhood:string|null;city:string|null;uf:string|null;cep:string|null;phone:string|null;state_registration:string|null;latitude:number|null;longitude:number|null;active:boolean;geocode_status:string|null;data_status:string|null;source:string|null;map_link:string|null;notes:string|null;created_at:string;updated_at:string };
export type TicketRow = { id:string;ticket_number:string;branch_id:string|null;analyst_id:string|null;technician_id:string|null;branch_name:string|null;city:string|null;uf:string|null;address:string|null;latitude:number|null;longitude:number|null;description:string;status:string;urgency:string;planned_date:string|null;estimated_minutes:number|null;opened_at:string|null;deadline_at:string|null;notes:string|null;planning_status:string;route_id:string|null;route_order:number|null;created_by:string|null;updated_by:string|null;created_at:string;updated_at:string };
export type RouteRow = { id:string;technician_id:string;route_date:string;status:string;start_type:string|null;start_description:string|null;start_address:string|null;start_city:string|null;start_uf:string|null;start_latitude:number|null;start_longitude:number|null;total_distance_km:number|null;estimated_minutes:number|null;notes:string|null;created_at:string;updated_at:string };
export type RouteStopRow = { id:string;route_id:string;ticket_id:string;stop_order:number;latitude:number|null;longitude:number|null;created_at:string;updated_at:string };
export type ProfileRow = { id:string;nome:string;email:string;role:AppRole;analyst_id:string|null;ativo:boolean;created_at:string;updated_at:string };
